Olga_Shestakova_Modul2_Island
MyLilla/Island pull request #1
Opened 2022-08-12 07:18 UTC by MyLilla

2022-08-21 07:31 UTC, MyLilla commented on src/ua/com/shestakova/Island/LifeTime.java
> +
это временный метод. Должно быть заменено на много поточный запуск

2022-08-22 19:02 UTC, andriilatyshev commented on README.md
> +- класс ```App``` - точка входа в приложение ```ua.com.shestakova.Island.App```
fdsfswd

2022-08-22 19:03 UTC, andriilatyshev commented on README.md
> +
fsdf

2022-08-22 19:03 UTC, MyLilla commented on src/ua/com/shestakova/Island/settingIsland/Tools.java
> +
нужно ли разбивать этот класс на 2? один для хранения данных, второй для методов. Но в принципе, это же все инструменты)
Или может мапу и переменные в ресурсы переложить?

2022-08-24 14:41 UTC, AndryLat commented on src/ua/com/shestakova/Island/Dialog.java
> +    Statistics statistics = new Statistics();
модификатор доступа?

2022-08-24 14:41 UTC, AndryLat commented on src/ua/com/shestakova/Island/Dialog.java
> +        if (number == 2) {
кто такой 2? имя переменной не говорит и ее назначении

2022-08-24 14:41 UTC, AndryLat commented on src/ua/com/shestakova/Island/Statistics.java
> +}
пустая строка должна быть

2022-08-24 14:41 UTC, AndryLat commented on src/ua/com/shestakova/Island/animal/Animal.java
> +    private int newValue(int x, int index) {
о чем говорит имя этого метода?

2022-08-24 14:41 UTC, AndryLat commented on src/ua/com/shestakova/Island/animal/Plant.java
> +}
ну растение это не животное же:) тут логика нарушается)

2022-08-31 10:15 UTC, MyLilla commented on README.md
> +
нужно ли такое писать тут?

2022-09-04 20:34 UTC, akupreychik approved these changes
Мне понравилась многопоточка! Молодец

2022-09-04 20:34 UTC, akupreychik commented on src/ua/com/shestakova/island/Dialog.java
> +import java.util.concurrent.*;
огромный и ненужный тебе пакет

2022-09-04 20:34 UTC, akupreychik commented on src/ua/com/shestakova/island/performingActions/LifeTime.java
> +        for (int i = 0; i < field.length; i++) {
очень сложная логика - разбей на методы

2022-09-04 20:34 UTC, akupreychik commented on src/ua/com/shestakova/island/performingActions/LifeTime.java
> +        for (int i = 0; i < field.length; i++) {
фор фор фор иф иф - это очень много

2022-09-04 20:35 UTC, akupreychik commented
+ пингани меня как зальешь проект, хочу глянуть с помощью jar-ки

2022-09-04 20:35 UTC, akupreychik commented on README.md
> +
да, это будет полезно

2022-09-27 11:49 UTC, AndryLat requested changes
Ты сама просила по жестче:)

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +public class Dialog {
ну вот ты создаешь класс диалог. Это не совсем интутитивно понятно,что внутри диалога ты содаешь остров, а потом запускаешь симуляцию.

Почему не сделать класс диалог, который введет пользователя в курс дела, потом возьмет у него нужные данные, ты эти данные сохранишь в отдельный объект и дальше этот объект передаешь уже в отдельный класс, который отвечает за симуляцию ?

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +    public void welcome(PrintStream out) {
имя метода должно содержать экшн.

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +        if (choice == 2) {
Что такое два и как в рамках этого кода я должен об этом догадаться?

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +            Tools.daysOfGame = Tools.getNumberFromUser(0, Integer.MAX_VALUE);
АААА. Ну нельзя так делать!!! У тебя в каком то классе ИНСТУРМЕНТЫ, есть поле дней и ты откуда-то это значение получаешь и туда проставляешь в ДИАЛОГЕ. Если анализировать такой код, можно сойти с ума, если начать именно в класса Тулс.

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +    private void getFirstInfo(PrintStream out) {
кто такая "первая инсормация"? Можно назвать InitInfo

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +        Statistics.firstGlobalInfo = statistics.getGlobalInformation();
тут ты делаешь просто потрясающую штуку: в статическую переменную класса статистика ты присваиваешь значение метода из объекта статистика В КЛАССЕ ДИАЛОГ!

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +        int choice = Tools.getNumberFromUser(1, 2);
Кто такие 1 и 2 ?

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +        for (int i = 0; i < daysOfGame; i++) {
вот такой цикл очень сложно читать, чтобы понять что это за дни и откуда они берутся.

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Dialog.java
> +                throw new ThreadsException("Sleep Exception in days tact" + e);
никогда не проглатывай оригинальный эксепшн! Всегда его вкладывай вторым параметром, после сообщения .

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Statistics.java
> +    public static Map<String, Integer> firstGlobalInfo;
почему это публичное и СТАТИЧЕСКОЕ? что мешает сделать это объектом? ты же теряешь весь смысл ООП и у тебя программа работает только с одним экземпляром всего (острова, статистики и т.д.) и по факту, если я захочу - две симуляции одновременно я уже не запущу никак без переписывания ВСЕГО. а ООП позволяет писать код именно так, ч тобы у нас можно было создать объектов столько, сколько хочешь!

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Statistics.java
> +                ArrayList<Сreature> loc = field[i][j].location;
реализация всегда вызвыается через интерфейс если такой есть. У эррейлиста такой точно есть.

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Statistics.java
> +        for (int i = 0; i < field.length; i++) {
тут лучше подойдет имя х и у

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Statistics.java
> +                for (int k = 0; k < field[i][j].location.size(); k++) {
кто такой к?

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Statistics.java
> +                if (field[i][j].location.size() > 0) filledLocations++;
всегда в любом ифе и цикле мы оборачиваем тело в фигурные скобки для ибегания проблем и багов!

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Statistics.java
> +        out.println("In total there are " + info.get("countAllAnimal") + " living creatures in the location\n\n" +
вывод информации сильно переплетен с бизнес логикой. Код сильносвязный и неповоротливый.

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/Statistics.java
> +                    if (map.containsKey(animal.getName())) {
этот иф заменяется методом merge

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/constructorGame/Island.java
> +    public static Island getIsland() {
У класса есть строгий порядок элементов: сначала константы (публичные, потом приватные), потом поля класса, потом конструкторы, а дальше публичная бизнес логика до сугубо технических приватных методов.

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/constructorGame/Location.java
> +        return countTypeInLoc;
Кто такой Loc и как мне это понять? Особенно, если я плохо дружу с инглишем

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/constructorGame/Parser.java
> +            JSONObject obj2 = new JSONObject();
Очень емкое имя.

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/constructorGame/Parser.java
> +            e.printStackTrace();
а? Это корректная обработка исключений?

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/constructorGame/Parser.java
> +            e.printStackTrace();
или "не записали в файл", да и Бог с ним? сами разберутся?

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/constructorGame/Parser.java
> +            throw new ParsingExceptions("File settingIsland.properties не существует is not exist" + ex);
Исключение не содержит очень важного элемента: по какому пути файл пытался быть найденным

2022-09-27 11:49 UTC, AndryLat commented on src/main/java/ua/com/shestakova/island/constructorGame/Tools.java
> +                System.exit(0);
НЕ ИСПОЛЬЗУЕМ такой подход! Прилжение всегда должно завершаться окончанием метода мейн

2022-10-01 13:02 UTC, merged